import type { Metadata } from 'next'
import { Red_Hat_Display as RedHatDisplay } from 'next/font/google'

import '@/styles/globals.css'

const redHatDisplay = RedHatDisplay({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${redHatDisplay.variable} bg-background-primary text-content-body antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
